# Generated by Django 2.2.4 on 2019-12-06 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='caption',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
